### ISSUE TITLE
Request: Desktop version

### ISSUE THREAD

**Issue by AlexQ3D** [liamnajor/ROSE#1]
Using something like Electron, it'd be great to have a desktop version for offline use

**Comment by liamnajor** [comment]
you can use it offline anyway, it was made for that. should I make it into a chrome extension?

**Comment by AlexQ3D** [comment]
I just like the idea of having it as an exe and seperate thing from my browser

**Comment by liamnajor** [comment]
it works as a chrome extension now, so if you want to use it that way, go ahead
